#!/usr/bin/env node

'use strict';
const minify = require('../src/minify.js');

(async () => {
  const args = process.argv.slice(2);
  const file = args[0];

  const result = await minify(file);
  console.log(result)    
})();